# About {.unnumbered}

## About the Project

*Social Science for Sustainability by Matt Turner* emerged from the need for a
simple, but powerful and
interdisciplinary social science to teach sustainability researchers and 
students quantitative social science. This includes necessary computational and
cognitive science topics sustainability practicioners need to know because they
matter for decision making in partnerships, institutions, in governments, and
online.

I emphasize in the title that this only my take by including my name, *Matt Turner*. 
I want this to be anti-colonial. I am trying to liberate social science from
disciplinary gatekeepers, not trying to become a
gatekeeper, myself. I want you to be inspired to create your own *Social Science
for Sustainability by {Your Name Here}*. In some social science disciplines, 
it seems there are some "holy
books" that, convention states, must be cited and whose approach must be
adopted. If my version of *Social Science* doesn't work for you, don't use it! 
Make up your own and show how it helps. Or maybe suggest ideas for this version.

That being said, I think the version in this project could be especially useful. 
I have put years into trying to understand the details of how social
science can help us in our existential crisis of accelerating unsustainability,
which perhaps has already spiraled beyond all control. 


## About the Author, Matt

I am a scientist and educator dedicated to resilient, rigorous, and
problem-focused social science. I am currently a Lecturer in Environmental Social
Sciences at the Stanford Doerr School of Sustainability at Stanford University.

In many ways my career has built up to this point. From my physics and mathematics training I learned to
use equations to calculate and understand collective dynamics, and an intuition
for how to construct mechanistic scientific models of reality. As a professional
software developer I upgraded my programming technicques along with domain
knowledge of economics and environmental and earth sciences. In my PhD training
I began consolidating all this, along with a strenuous training in 
social, cognitive, and behavioral sciences.

Until receiving my PhD in Cognitive and Information Sciences in 2021, 
I got my kicks cultivating a beginner's mind by switching majors, careers,
disciplines, cities, and more. All the while, many peers focused their efforts towards
developing deeper expertise in fewer topics. My PhD work was the beginning of
the synthesis of my work up to that point. The work presented in this Book,
Curriculum, and other materials, is a continuation and extention.

This work was made possible by my time spent as a postdoctoral
scholar mentored by James Holland Jones, with funding from a Stanford Medicine
Pandemic Preparedness Hub Fellowship that enabled me to even kickstart a 
project to cross even more disciplinary and international borders studying 
urban Indigenous infection dynamics in Brazil. I hope to continue to build my
collaboration with my Brazilian colleagues and expand my collaboration to
include more scientists from the United States and Brazil for cultural and
scientific exchange. People in these two countries face many similar cultural
challenges as the largest democracies in the Americas. I myself got to spend 
summer 2008 learning Portuguese and living and working on astrophysics research in
Brazil.

I am motivated by a deep and humbling sense of duty to present essential social science
material with a minimum cognitive overhead a maximum real-world impact.
This job requires a diverse background like mine to understand the science,
mathematics, computation, and philosophy of all the various social science
disciplines that have something to contribute.

## Closing: Consilience

This work implements a method of consilient, strategic curation of
social science. Curation is a type of consolidation.
In terms of scientific theories, this means the theory uses fewer types of
imagined things, processes, or situations to predict real-world observations. 
For example, the theory of quantum mechanics consolidates physics research,
helping us understand research in atomic physics and chemistry can be explained
by a common set of mathematical models and computational tools.

When we consolidtate theories, in social science or physics, we get a default
benefit of having fewer ideas, or mental "things", we have to keep track of 
in our limited working memory. *Consilience* is the added benefit that
we often see unpredictably useful and aesthetically beautiful connections between 
what seemed to be disconnected scientific phenomena. In other words, 
a consilient theory is more than just the sum of its parts.
